### ISSUE TITLE
Accent marks

### ISSUE THREAD

**Issue by victorlopezalonso** [AddonPayments/php-sdk#4]
Accent marks are still present in the project so people using macOS or linux based system is not going to be able to install the library using composer.

There are 2 problems:

- The packagist library is linked to v2.0.1 which is not the latest version of the package cause master has a more advanced version.
- The problem with the accent marks is still present in the master branch --> /test/php/API/03 - Gestión de transacciones

Please check this issue so we can use the official library instead of the fork that we created to fix this issue.

Thanks!

**Comment by VictorACH** [comment]
Hi Víctor.

Thanks for the request, we have updated the documentation and created a new tag so that the Composer version is modified with the latest changes.

The last version updated is 2.2.0.

If you have any doubts or questions regarding the payment method, you can call 914353028 or send an email to soporte@addonpayments.com.

Thanks.
